public with sharing class ActionPlansConstants {
	
	// Max ammount of APTasks per Action Plan
	public static final Integer maxAPTasks 		= 75;
	
	// Max ammount of objects (i.e.: Accounts, contacts, etc.) that can be selected to create an Action Plan
	public static final Integer maxAPObjects	= 40;
	
	// Max ammount of Action Plans that can be deleted from list
	public static final Integer maxAPToDelete	= 65;
}